// Mapeamento de nomes de arquivo para nomes de exibição
export const DISPLAY_NAMES: Record<string, string> = {
  "acelerar-as-bolas": "Acelerar as bolas",
  "adaptacao-tatica": "Adaptação Tática",
  "adaptacao": "Adaptação",
  "antecipacao": "Antecipação",
  "aquecimento": "Aquecimento",
  "ataque-ao-corpo": "Ataque ao Corpo",
  "ataque": "Ataque",
  "atp-around-the-post": "ATP (Around The Post)",
  "bloqueio": "Bloqueio",
  "comunicacao": "Comunicação",
  "concentracao": "Concentração",
  "consistencia": "Consistência",
  "contra-ataque": "Contra-ataque",
  "controle-de-ponto": "Controle de Ponto",
  "controle-de-ritmo": "Controle de Ritmo",
  "defesa": "Defesa",
  "devolucao": "Devolução",
  "dicas": "Dicas",
  "dink": "Dink",
  "drills-e-treinos": "Drills e Treinos",
  "treino-com-paredao": "Treino com Paredão",
  "drop-shot": "Drop Shot",
  "drive": "Drive",
  "empunhadura": "Empunhadura",
  "equipamentos": "Equipamentos",
  "erne": "Erne",
  "erros-comuns": "Erros Comuns",
  "estrategia-de-jogo": "Estratégia de Jogo",
  "estrategias-de-abertura": "Estratégias de Abertura",
  "execucao-sob-pressao": "Execução Sob Pressão",
  "explorar-fraquezas": "Explorar Fraquezas",
  "exploracao-de-angulos": "Exploração de Ângulos",
  "finalizacoes": "Finalizações",
  "footwork": "Footwork",
  "forcar-erros": "Forçar Erros",
  "golpes-especiais": "Golpes Especiais",
  "golpes-fundamentais": "Golpes Fundamentais",
  "isolamento-de-jogador": "Isolamento de Jogador",
  "jogo-cruzado": "Jogo Cruzado",
  "jogo-de-duplas": "Jogo de Duplas",
  "jogo-de-paciencia": "Jogo de Paciência",
  "jogo-no-meio": "Jogo no Meio",
  "jogo-singles": "Jogo Singles",
  "jogos-mentais": "Jogos Mentais",
  "leitura-de-jogo": "Leitura de Jogo",
  "lideranca-em-quadra": "Liderança em Quadra",
  "lob": "Lob",
  "mental-game": "Mental Game",
  "mudanca-de-direcao": "Mudança de Direção",
  "poaching": "Poaching",
  "pontuacao-detalhada": "Pontuação Detalhada",
  "etiqueta-em-quadra": "Etiqueta em Quadra",
  "seguranca-e-prevencao-lesoes": "Prevenção de Lesões",
  "selecao-de-golpes": "Seleção de Golpes",
  "lidar-com-bangers": "Lidar com Bangers",
  "variacoes-de-saque-intermediario": "Variações de Saque ",
  "tipos-de-voleios-pickleball": "Tipos de Voleios no Pickleball",
  "tipos-de-dink-pickleball": "Tipos de Dink no Pickleball",
  "mecanicas-fundamentais": "Mecânicas Fundamentais",
  "tecnicas-de-decepcao-engano": "Técnicas para esconder o golpe",
  "recuperacao-e-cobertura-quadra-avancada": "Recuperação e Cobertura de Quadra",
  "quimica-e-sinergia-duplas-avancadas": "Química e Sinergia em Duplas",
  "selecao-de-golpes-avancada": "Seleção de Golpes",
  "construcao-de-pontos": "Construção de Pontos",
  "transicao-defesa-ataque": "Transição Defesa-Ataque",
  "gerenciamento-momentum-timeouts": "Momentum e Timeouts",
  "posicionamento": "Posicionamento",
  "preparacao-fisica": "Preparação Física",
  "pressao-constante": "Pressão Constante",
  "pressao-mental": "Pressão Mental",
  "quebra-de-ritmo": "Quebra de Ritmo",
  "regras": "Regras",
  "reset": "Reset",
  "respiracao": "Respiração",
  "saque": "Saque",
  "smash": "Smash",
  "spin": "Spin",
  "stacking": "Stacking",
  "switching": "Switching",
  "tempo-de-reacao": "Tempo de Reação",
  "terceira-bola": "Terceira bola",
  "torneios": "Torneios",
  "transicao": "Transição",
  "tecnica-de-base": "Técnica de Base",
  "tecnicas-avancadas": "Técnicas Avançadas",
  "uso-do-lob-tatico": "Uso do Lob Tático",
  "variacao-de-altura": "Variação de Altura",
  "voleio": "Voleio"
};

export function getDisplayName(fileName: string): string {
  return DISPLAY_NAMES[fileName] || fileName;
}
