// Mapeamento de IDs únicos para cada seção (baseado no nome, sem numeração sequencial)
export const SECTION_IDS: Record<string, string> = {
  // Básico
  "regras": "rules",
  "saque": "serve",
  "devolucao": "return",
  "dink": "dink",
  "voleio": "volley",
  "footwork": "footwork",
  "posicionamento": "positioning",
  "empunhadura": "grip",
  "aquecimento": "warmup",
  "erros-comuns": "common-mistakes",
  "dicas": "tips",
  "equipamentos": "equipment",
  "golpes-fundamentais": "fundamental-shots",
  "tecnica-de-base": "basic-technique",
  "concentracao": "concentration",
  "respiracao": "breathing",
  "pontuacao-detalhada": "scoring",
  "etiqueta-em-quadra": "court-etiquette",
  "seguranca-e-prevencao-lesoes": "safety-injury-prevention",
  "historia-e-origem": "history-origin",
  "vocabulario-e-termos": "vocabulary-terms",
  "como-escolher-parceiro": "choosing-partner",
  "drills-e-treinos-basicos": "basic-drills-training",

  // Intermediário
  "drop-shot": "drop-shot",
  "drive": "drive",
  "terceira-bola": "third-shot",
  "lob": "lob",
  "transicao": "transition",
  "jogo-de-duplas": "doubles-play",
  "defesa": "defense",
  "bloqueio": "blocking",
  "spin": "spin",
  "contra-ataque": "counter-attack",
  "comunicacao": "communication",
  "drills-e-treinos": "drills-training",
  "treino-com-paredao": "wall-training",
  "preparacao-fisica": "physical-prep",
  "estrategia-de-jogo": "game-strategy",
  "tempo-de-reacao": "reaction-time",
  "antecipacao": "anticipation",
  "leitura-de-jogo": "game-reading",
  "adaptacao": "adaptation",
  "consistencia": "consistency",
  "selecao-de-golpes": "shot-selection",
  "lidar-com-bangers": "handling-bangers",
  "variacoes-de-saque-intermediario": "intermediate-serve-variations",
  "tipos-de-voleios-pickleball": "volley-types",
  "tipos-de-dink-pickleball": "dink-types",
  "mecanicas-fundamentais": "fundamental-mechanics",
  "analise-de-pontos": "point-analysis",
  "preparacao-mental-intermediaria": "intermediate-mental-prep",
  "estrategias-saque-devolucao-avancadas": "advanced-serve-return-strategies",
  "controle-mental": "mental-control",
  "exercicios-mobilidade-forca": "mobility-strength-exercises",
  
  // Avançado
  "tecnicas-de-decepcao-engano": "deception-techniques",
  "recuperacao-e-cobertura-quadra-avancada": "advanced-court-coverage",
  "quimica-e-sinergia-duplas-avancadas": "advanced-doubles-synergy",
  "selecao-de-golpes-avancada": "advanced-shot-selection",
  "construcao-de-pontos": "point-construction",
  "analise-de-video": "video-analysis",
  "preparacao-fisica-avancada-competicoes": "advanced-physical-prep-competitions",
  "scouting-analise-oponentes": "scouting-opponent-analysis",
  "drills-e-treinos-avancados": "advanced-drills-training",
  "jogo-da-porcentagem": "percentage-play",
  "transicao-defesa-ataque": "defense-to-attack-transition",
  "gerenciamento-momentum-timeouts": "momentum-timeout-management",
  "acelerar-as-bolas": "speeding-up-balls",
  "ataque": "attack",
  "atp-around-the-post": "atp-around-post",
  "erne": "erne",
  "execucao-sob-pressao": "execution-under-pressure",
  "finalizacoes": "finishes",
  "golpes-especiais": "special-shots",
  "jogo-singles": "singles-play",
  "lideranca-em-quadra": "court-leadership",
  "mental-game": "mental-game",
  "poaching": "poaching",
  "pressao-mental": "mental-pressure",
  "reset": "reset",
  "smash": "smash",
  "stacking": "stacking",
  "switching": "switching",
  "tecnicas-avancadas": "advanced-techniques",
  "torneios": "tournaments",

  // Táticas
  "pressao-constante": "constant-pressure",
  "jogo-cruzado": "cross-court-play",
  "isolamento-de-jogador": "player-isolation",
  "variação-de-altura": "height-variation",
  "variação-de-velocidade": "speed-variation",
  "variação-de-direção": "direction-variation",
  "variação-de-spin": "spin-variation",
  "variação-de-tempo": "timing-variation",
  "variação-de-posição": "position-variation",
  "variação-de-ritmo": "rhythm-variation",
  "variação-de-estratégia": "strategy-variation",
  "variação-de-formação": "formation-variation",
  "variação-de-cobertura": "coverage-variation",
  "variação-de-comunicação": "communication-variation",
  "variação-de-mental": "mental-variation",
  "variação-de-física": "physical-variation",
  "variação-de-técnica": "technique-variation",
  "variação-de-tática": "tactical-variation",
};

// Mapeamento reverso: ID -> Section
export const ID_TO_SECTION: Record<string, string> = Object.fromEntries(
  Object.entries(SECTION_IDS).map(([section, id]) => [id, section])
);

// Básico
export const BASIC_SECTIONS = [
  "regras",
  "saque",
  "devolucao",
  "dink",
  "voleio",
  "footwork",
  "posicionamento",
  "empunhadura",
  "aquecimento",
  "erros-comuns",
  "dicas",
  "equipamentos",
  "golpes-fundamentais",
  "tecnica-de-base",
  "concentracao",
  "respiracao",
  "pontuacao-detalhada",
  "etiqueta-em-quadra",
  "seguranca-e-prevencao-lesoes",
  "historia-e-origem",
  "vocabulario-e-termos",
  "como-escolher-parceiro",
  "drills-e-treinos-basicos",
] as const;

// Intermediário
export const INTERMEDIATE_SECTIONS = [
  "drop-shot",
  "drive",
  "terceira-bola",
  "lob",
  "transicao",
  "jogo-de-duplas",
  "defesa",
  "bloqueio",
  "spin",
  "contra-ataque",
  "comunicacao",
  "drills-e-treinos",
  "treino-com-paredao",
  "preparacao-fisica",
  "estrategia-de-jogo",
  "tempo-de-reacao",
  "antecipacao",
  "leitura-de-jogo",
  "adaptacao",
  "consistencia",
  "selecao-de-golpes",
  "lidar-com-bangers",
  "variacoes-de-saque-intermediario",
  "tipos-de-voleios-pickleball",
  "tipos-de-dink-pickleball",
  "mecanicas-fundamentais",
  "analise-de-pontos",
  "preparacao-mental-intermediaria",
  "estrategias-saque-devolucao-avancadas",
  "controle-mental",
  "exercicios-mobilidade-forca",
] as const;

// Avançado
export const ADVANCED_SECTIONS = [
  "smash",
  "acelerar-as-bolas",
  "reset",
  "ataque",
  "mental-game",
  "erne",
  "atp-around-the-post",
  "stacking",
  "switching",
  "poaching",
  "finalizacoes",
  "jogo-singles",
  "torneios",
  "golpes-especiais",
  "tecnicas-avancadas",
  "pressao-mental",
  "execucao-sob-pressao",
  "lideranca-em-quadra",
  "tecnicas-de-decepcao-engano",
  "recuperacao-e-cobertura-quadra-avancada",
  "quimica-e-sinergia-duplas-avancadas",
  "selecao-de-golpes-avancada",
  "construcao-de-pontos",
  "analise-de-video",
  "preparacao-fisica-avancada-competicoes",
  "scouting-analise-oponentes",
  "jogo-da-porcentagem",
  "drills-e-treinos-avancados",
] as const;

// Táticas
export const TACTICS_SECTIONS = [
  "controle-de-ritmo",
  "jogo-no-meio",
  "explorar-fraquezas",
  "variacao-de-altura",
  "pressao-constante",
  "jogo-cruzado",
  "isolamento-de-jogador",
  "mudanca-de-direcao",
  "jogo-de-paciencia",
  "ataque-ao-corpo",
  "uso-do-lob-tatico",
  "forcar-erros",
  "estrategias-de-abertura",
  "controle-de-ponto",
  "quebra-de-ritmo",
  "exploracao-de-angulos",
  "jogos-mentais",
  "adaptacao-tatica",
  "transicao-defesa-ataque",
  "gerenciamento-momentum-timeouts",
] as const;

// Todas as seções
export const SECTIONS = [
  ...BASIC_SECTIONS,
  ...INTERMEDIATE_SECTIONS,
  ...ADVANCED_SECTIONS,
  ...TACTICS_SECTIONS,
] as const;

export type Section = typeof SECTIONS[number];

// Níveis das seções
export type SectionLevel = 'Básico' | 'Intermediário' | 'Avançado' | 'Táticas';

export const SECTION_LEVELS: Record<Section, SectionLevel> = {
  "regras": "Básico",
  "saque": "Básico",
  "devolucao": "Básico",
  "dink": "Básico",
  "voleio": "Básico",
  "footwork": "Básico",
  "posicionamento": "Básico",
  "empunhadura": "Básico",
  "aquecimento": "Básico",
  "erros-comuns": "Básico",
  "dicas": "Básico",
  "equipamentos": "Básico",
  "golpes-fundamentais": "Básico",
  "tecnica-de-base": "Básico",
  "concentracao": "Básico",
  "respiracao": "Básico",
  "pontuacao-detalhada": "Básico",
  "etiqueta-em-quadra": "Básico",
  "seguranca-e-prevencao-lesoes": "Básico",
  "historia-e-origem": "Básico",
  "vocabulario-e-termos": "Básico",
  "como-escolher-parceiro": "Básico",
  "drills-e-treinos-basicos": "Básico",
  "drop-shot": "Intermediário",
  "drive": "Intermediário",
  "terceira-bola": "Intermediário",
  "lob": "Intermediário",
  "transicao": "Intermediário",
  "jogo-de-duplas": "Intermediário",
  "defesa": "Intermediário",
  "bloqueio": "Intermediário",
  "spin": "Intermediário",
  "contra-ataque": "Intermediário",
  "comunicacao": "Intermediário",
  "drills-e-treinos": "Intermediário",
  "treino-com-paredao": "Intermediário",
  "preparacao-fisica": "Intermediário",
  "estrategia-de-jogo": "Intermediário",
  "tempo-de-reacao": "Intermediário",
  "antecipacao": "Intermediário",
  "leitura-de-jogo": "Intermediário",
  "adaptacao": "Intermediário",
  "consistencia": "Intermediário",
  "selecao-de-golpes": "Intermediário",
  "lidar-com-bangers": "Intermediário",
  "variacoes-de-saque-intermediario": "Intermediário",
  "tipos-de-voleios-pickleball": "Intermediário",
  "tipos-de-dink-pickleball": "Intermediário",
  "mecanicas-fundamentais": "Intermediário",
  "analise-de-pontos": "Intermediário",
  "preparacao-mental-intermediaria": "Intermediário",
  "estrategias-saque-devolucao-avancadas": "Intermediário",
  "controle-mental": "Intermediário",
  "exercicios-mobilidade-forca": "Intermediário",
  "smash": "Avançado",
  "acelerar-as-bolas": "Avançado",
  "reset": "Avançado",
  "ataque": "Avançado",
  "mental-game": "Avançado",
  "erne": "Avançado",
  "atp-around-the-post": "Avançado",
  "stacking": "Avançado",
  "switching": "Avançado",
  "poaching": "Avançado",
  "finalizacoes": "Avançado",
  "jogo-singles": "Avançado",
  "torneios": "Avançado",
  "golpes-especiais": "Avançado",
  "tecnicas-avancadas": "Avançado",
  "pressao-mental": "Avançado",
  "execucao-sob-pressao": "Avançado",
  "lideranca-em-quadra": "Avançado",
  "tecnicas-de-decepcao-engano": "Avançado",
  "recuperacao-e-cobertura-quadra-avancada": "Avançado",
  "quimica-e-sinergia-duplas-avancadas": "Avançado",
  "selecao-de-golpes-avancada": "Avançado",
  "construcao-de-pontos": "Avançado",
  "analise-de-video": "Avançado",
  "preparacao-fisica-avancada-competicoes": "Avançado",
  "scouting-analise-oponentes": "Avançado",
  "jogo-da-porcentagem": "Avançado",
  "drills-e-treinos-avancados": "Avançado",
  "controle-de-ritmo": "Táticas",
  "jogo-no-meio": "Táticas",
  "explorar-fraquezas": "Táticas",
  "variacao-de-altura": "Táticas",
  "pressao-constante": "Táticas",
  "jogo-cruzado": "Táticas",
  "isolamento-de-jogador": "Táticas",
  "mudanca-de-direcao": "Táticas",
  "jogo-de-paciencia": "Táticas",
  "ataque-ao-corpo": "Táticas",
  "uso-do-lob-tatico": "Táticas",
  "forcar-erros": "Táticas",
  "estrategias-de-abertura": "Táticas",
  "controle-de-ponto": "Táticas",
  "quebra-de-ritmo": "Táticas",
  "exploracao-de-angulos": "Táticas",
  "jogos-mentais": "Táticas",
  "adaptacao-tatica": "Táticas",
  "transicao-defesa-ataque": "Táticas",
  "gerenciamento-momentum-timeouts": "Táticas",
};

export function getSectionLevel(section: Section): SectionLevel {
  return SECTION_LEVELS[section] || 'Básico';
}
