// Básico
export const BASIC_SECTIONS = [
  "regras",
  "saque",
  "devolucao",
  "dink",
  "voleio",
  "footwork",
  "posicionamento",
  "empunhadura",
  "aquecimento",
  "erros-comuns",
  "dicas",
  "equipamentos",
  "golpes-fundamentais",
  "tecnica-de-base",
  "concentracao",
  "respiracao",
  "pontuacao-detalhada",
  "etiqueta-em-quadra",
  "seguranca-e-prevencao-lesoes",
] as const;

// Intermediário
export const INTERMEDIATE_SECTIONS = [
  "drop-shot",
  "terceira-bola",
  "lob",
  "transicao",
  "jogo-de-duplas",
  "defesa",
  "bloqueio",
  "spin",
  "contra-ataque",
  "comunicacao",
  "drills-e-treinos",
  "preparacao-fisica",
  "estrategia-de-jogo",
  "tempo-de-reacao",
  "antecipacao",
  "leitura-de-jogo",
  "adaptacao",
  "consistencia",
  "selecao-de-golpes",
  "lidar-com-bangers",
  "variacoes-de-saque-intermediario",
  "tipos-de-voleios-pickleball",
  "tipos-de-dink-pickleball",
] as const;

// Avançado
export const ADVANCED_SECTIONS = [
  "smash",
  "acelerar-as-bolas",
  "reset",
  "ataque",
  "mental-game",
  "erne",
  "atp-around-the-post",
  "stacking",
  "switching",
  "poaching",
  "finalizacoes",
  "jogo-singles",
  "torneios",
  "golpes-especiais",
  "tecnicas-avancadas",
  "pressao-mental",
  "execucao-sob-pressao",
  "lideranca-em-quadra",
  "tecnicas-de-decepcao-engano",
  "recuperacao-e-cobertura-quadra-avancada",
  "quimica-e-sinergia-duplas-avancadas",
] as const;

// Táticas
export const TACTICS_SECTIONS = [
  "controle-de-ritmo",
  "jogo-no-meio",
  "explorar-fraquezas",
  "variacao-de-altura",
  "pressao-constante",
  "jogo-cruzado",
  "isolamento-de-jogador",
  "mudanca-de-direcao",
  "jogo-de-paciencia",
  "ataque-ao-corpo",
  "uso-do-lob-tatico",
  "forcar-erros",
  "estrategias-de-abertura",
  "controle-de-ponto",
  "quebra-de-ritmo",
  "exploracao-de-angulos",
  "jogos-mentais",
  "adaptacao-tatica",
  "transicao-defesa-ataque",
  "gerenciamento-momentum-timeouts",
] as const;

// Todas as seções
export const SECTIONS = [
  ...BASIC_SECTIONS,
  ...INTERMEDIATE_SECTIONS,
  ...ADVANCED_SECTIONS,
  ...TACTICS_SECTIONS,
] as const;

export type Section = typeof SECTIONS[number];

// Níveis das seções
export type SectionLevel = 'Básico' | 'Intermediário' | 'Avançado' | 'Táticas';

export const SECTION_LEVELS: Record<Section, SectionLevel> = {
  "regras": "Básico",
  "saque": "Básico",
  "devolucao": "Básico",
  "dink": "Básico",
  "voleio": "Básico",
  "footwork": "Básico",
  "posicionamento": "Básico",
  "empunhadura": "Básico",
  "aquecimento": "Básico",
  "erros-comuns": "Básico",
  "dicas": "Básico",
  "equipamentos": "Básico",
  "golpes-fundamentais": "Básico",
  "tecnica-de-base": "Básico",
  "concentracao": "Básico",
  "respiracao": "Básico",
  "pontuacao-detalhada": "Básico",
  "etiqueta-em-quadra": "Básico",
  "seguranca-e-prevencao-lesoes": "Básico",
  "drop-shot": "Intermediário",
  "terceira-bola": "Intermediário",
  "lob": "Intermediário",
  "transicao": "Intermediário",
  "jogo-de-duplas": "Intermediário",
  "defesa": "Intermediário",
  "bloqueio": "Intermediário",
  "spin": "Intermediário",
  "contra-ataque": "Intermediário",
  "comunicacao": "Intermediário",
  "drills-e-treinos": "Intermediário",
  "preparacao-fisica": "Intermediário",
  "estrategia-de-jogo": "Intermediário",
  "tempo-de-reacao": "Intermediário",
  "antecipacao": "Intermediário",
  "leitura-de-jogo": "Intermediário",
  "adaptacao": "Intermediário",
  "consistencia": "Intermediário",
  "selecao-de-golpes": "Intermediário",
  "lidar-com-bangers": "Intermediário",
  "variacoes-de-saque-intermediario": "Intermediário",
  "tipos-de-voleios-pickleball": "Intermediário",
  "tipos-de-dink-pickleball": "Intermediário",
  "smash": "Avançado",
  "acelerar-as-bolas": "Avançado",
  "reset": "Avançado",
  "ataque": "Avançado",
  "mental-game": "Avançado",
  "erne": "Avançado",
  "atp-around-the-post": "Avançado",
  "stacking": "Avançado",
  "switching": "Avançado",
  "poaching": "Avançado",
  "finalizacoes": "Avançado",
  "jogo-singles": "Avançado",
  "torneios": "Avançado",
  "golpes-especiais": "Avançado",
  "tecnicas-avancadas": "Avançado",
  "pressao-mental": "Avançado",
  "execucao-sob-pressao": "Avançado",
  "lideranca-em-quadra": "Avançado",
  "tecnicas-de-decepcao-engano": "Avançado",
  "recuperacao-e-cobertura-quadra-avancada": "Avançado",
  "quimica-e-sinergia-duplas-avancadas": "Avançado",
  "controle-de-ritmo": "Táticas",
  "jogo-no-meio": "Táticas",
  "explorar-fraquezas": "Táticas",
  "variacao-de-altura": "Táticas",
  "pressao-constante": "Táticas",
  "jogo-cruzado": "Táticas",
  "isolamento-de-jogador": "Táticas",
  "mudanca-de-direcao": "Táticas",
  "jogo-de-paciencia": "Táticas",
  "ataque-ao-corpo": "Táticas",
  "uso-do-lob-tatico": "Táticas",
  "forcar-erros": "Táticas",
  "estrategias-de-abertura": "Táticas",
  "controle-de-ponto": "Táticas",
  "quebra-de-ritmo": "Táticas",
  "exploracao-de-angulos": "Táticas",
  "jogos-mentais": "Táticas",
  "adaptacao-tatica": "Táticas",
  "transicao-defesa-ataque": "Táticas",
  "gerenciamento-momentum-timeouts": "Táticas",
};

export function getSectionLevel(section: Section): SectionLevel {
  return SECTION_LEVELS[section] || 'Básico';
}
