import { Section } from "./sections";

export const sectionTips: Record<Section, string[]> = {
  "Regras": [
    "A zona da cozinha tem 7 pés de profundidade - não pode pisar na linha ao volear",
    "Saque deve ser por baixo (underhand) e na diagonal",
    "Apenas o time que está sacando pode pontuar",
    "A bola deve quicar uma vez de cada lado antes de poder volear",
    "Pontuação: seu placar, placar adversário, número do servidor (1 ou 2)",
    "Pode ficar na cozinha, mas não pode volear enquanto estiver dentro",
    "Após volear, pode cair na cozinha, mas contato deve ser fora",
    "Bola que toca a linha é considerada 'in' - sempre jogue",
    "Saque deve ser diagonal - não pode ser direto",
    "Bola que toca o corpo ou roupa do jogador é ponto para o adversário",
    "Jogador pode tocar a rede apenas se a bola já passou para o lado adversário",
    "Bola que toca a linha de fundo é considerada 'in' - sempre jogue",
    "Em duplas, ordem de saque deve ser respeitada (servidor 1, depois 2)",
    "Time perde o saque se cometer falta (bola fora, na rede, etc.)",
    "Jogo vai até 11 pontos, mas deve ganhar por 2 pontos de diferença",
    "Em torneios, pode ir até 15 ou 21 pontos dependendo do formato"
  ],
  "Saque": [
    "Contato com a bola abaixo da cintura, cabeça da raquete abaixo do punho",
    "Mire profundo, perto da linha de fundo",
    "Varie entre corpo e cantos para manter adversário adivinhando",
    "Desenvolva rotina pré-saque (respirar, quicar) para consistência",
    "Pratique consistência antes de potência",
    "Experimente saques com spin para dificultar devolução",
    "Saque na diagonal para o quadrante correto",
    "Posicione-se atrás da linha de base - não pise na linha",
    "Use movimento fluido de baixo para cima - não pare o movimento",
    "Mire para o backhand do adversário - geralmente mais fraco",
    "Saque com topspin cai mais rápido e é mais difícil de devolver",
    "Varie altura: saque baixo e rasteiro vs alto e profundo",
    "Observe posição do adversário - saque para onde ele não está",
    "Saque para o meio em duplas cria confusão sobre quem pega",
    "Mantenha mesmo ritmo e preparação para todos os saques",
    "Saque para os pés do adversário é mais difícil de devolver",
    "Pratique saque de diferentes posições na linha de base",
    "Saque com underspin (backspin) pode confundir adversários"
  ],
  "Devolução": [
    "Sempre devolva profundo para ganhar tempo de avançar",
    "Mire no meio ou no jogador mais fraco",
    "Use topspin para manter a bola baixa após o quique",
    "Prepare-se para avançar 2-3 passos após devolver",
    "Devolva para o backhand se não souber a fraqueza",
    "Evite devoluções curtas que dão vantagem aos adversários",
    "Posicione-se atrás da linha de base para tempo de reação",
    "Devolução cruzada é mais segura - mais distância e ângulo",
    "Use movimento de baixo para cima para gerar topspin",
    "Devolva para os pés do adversário - mais difícil de atacar",
    "Varie entre devolução cruzada e paralela",
    "Devolução no meio em duplas cria confusão",
    "Mantenha raquete na frente do corpo para reação rápida",
    "Devolva com altura suficiente para passar sobre a rede",
    "Observe posição dos adversários antes de escolher direção",
    "Devolução com underspin pode confundir adversários",
    "Pratique devolução de diferentes alturas de saque",
    "Devolva para o lado mais fraco do adversário"
  ],
  "Dink": [
    "Joelhos flexionados, corpo baixo, pulso firme",
    "Dink cruzado é mais seguro (mais distância e ângulo)",
    "Mire para os pés do adversário, mantenha bola baixa",
    "Seja paciente - não force o ataque prematuramente",
    "Raquete aberta (face para cima) para melhor controle",
    "Varie profundidade: linha da cozinha e mais fundo",
    "Observe pés do adversário - se recuando, ataque",
    "Dink paralelo é mais agressivo mas mais arriscado",
    "Use movimento de baixo para cima para gerar arco",
    "Mantenha bola 6-12 polegadas acima da rede",
    "Dink para o meio em duplas cria confusão",
    "Varie entre dink baixo e médio para confundir",
    "Dink com underspin é mais difícil de atacar",
    "Observe posição da raquete do adversário para antecipar",
    "Dink para o backhand é geralmente mais seguro",
    "Pratique dink de diferentes distâncias da rede",
    "Dink defensivo: mais alto e profundo",
    "Dink ofensivo: mais baixo e próximo da rede"
  ],
  "Voleio": [
    "Raquete alta e na frente do corpo, movimentos curtos",
    "Bloqueie ao invés de balançar forte",
    "Posicione-se a um braço de distância da rede",
    "Voleie para baixo quando possível",
    "Antecipe direção observando preparação do oponente",
    "Use voleios de bloqueio contra drives rápidos",
    "Mantenha peso para frente, pés ativos",
    "Voleio cruzado é mais seguro - mais distância",
    "Voleio para os pés do adversário é mais efetivo",
    "Use voleio de bloqueio para bolas rápidas",
    "Voleio ofensivo: mire para espaços abertos",
    "Mantenha raquete firme mas não tensa",
    "Voleio no meio em duplas cria confusão",
    "Varie entre voleio alto e baixo",
    "Voleio com underspin é mais difícil de devolver",
    "Observe posição dos pés do adversário",
    "Voleio defensivo: mantenha bola em jogo",
    "Pratique voleio de diferentes alturas"
  ],
  "Footwork": [
    "Faça split step quando adversário bater na bola",
    "Use passos laterais, não cruze as pernas",
    "Posicione-se atrás da bola, não ao lado",
    "Recupere para o centro após cada golpe",
    "Base ampla (largura dos ombros) para estabilidade",
    "Joelhos flexionados, peso na frente dos pés",
    "Passos pequenos e rápidos para ajustes finos",
    "Split step: pequeno pulo quando adversário bate",
    "Use passos de deslizamento para movimentos laterais",
    "Mantenha pés ativos - nunca fique parado",
    "Pés devem estar em movimento antes da bola chegar",
    "Use passos de ajuste para posicionamento fino",
    "Recuperação: sempre volte para posição central",
    "Antecipe direção observando preparação do adversário",
    "Pés devem estar prontos para qualquer direção",
    "Pratique footwork sem bola para automatizar",
    "Use passos de explosão para bolas distantes",
    "Mantenha equilíbrio durante todo o movimento"
  ],
  "Posicionamento": [
    "A rede é a posição dominante - avance sempre que possível",
    "Mantenha-se alinhado com parceiro em duplas",
    "Posicione-se logo atrás da linha da cozinha na rede",
    "Evite 'terra de ninguém' (meio da quadra)",
    "Cubra o meio da quadra - área mais vulnerável",
    "Movam-se como unidade - frente/trás juntos",
    "Ajuste posição baseado na posição dos adversários",
    "Posição na rede: um braço de distância da linha da cozinha",
    "Em duplas, cubra seu lado e o meio da quadra",
    "Posição de fundo: atrás da linha de base",
    "Ajuste posição baseado na altura da bola",
    "Posicione-se para cobrir o ângulo mais provável",
    "Mantenha distância adequada do parceiro",
    "Posição ofensiva: mais próximo da rede",
    "Posição defensiva: mais afastado da rede",
    "Ajuste posição baseado no estilo do adversário",
    "Posicione-se para maximizar cobertura da quadra",
    "Mantenha posição que permita movimento rápido"
  ],
  "Empunhadura": [
    "Continental é a mais versátil para todos os golpes",
    "Segure firme mas relaxada - aperte só no contato",
    "Teste: deve caber um dedo entre dedos e palma",
    "Eastern grip (aperto de mão) funciona para iniciantes",
    "Posicione mão na base do grip para mais alcance",
    "Empunhadura relaxada = melhor sensibilidade",
    "Verifique tamanho do grip - deve ser confortável"
  ],
  "Aquecimento": [
    "5-10 minutos de cardio leve para começar",
    "Alongamentos dinâmicos, não estáticos",
    "Aqueça ombros, pulsos e tornozelos com rotações",
    "Pratique split steps e movimentos laterais",
    "Comece com dinks suaves, aumente intensidade gradualmente",
    "Hidrate-se antes, durante e após",
    "Alongue panturrilhas, quadríceps e isquiotibiais"
  ],
  "Erros Comuns": [
    "Bater muito forte - controle > potência",
    "Ficar no fundo da quadra - avance para a rede!",
    "Não se comunicar com parceiro em duplas",
    "Segurar raquete muito apertada - causa tensão",
    "Não fazer split step - reação lenta",
    "Pisar na linha da cozinha ao volear",
    "Tentar smash em bolas que não estão altas o suficiente"
  ],
  "Dicas": [
    "Assista jogadores profissionais para aprender",
    "Jogue com jogadores melhores que você",
    "Filme seus jogos para identificar melhorias",
    "Pratique um aspecto específico a cada sessão",
    "Participe de clínicas e workshops",
    "Estabeleça metas mensuráveis mensais",
    "Celebre vitórias e aprenda com derrotas"
  ],
  "Equipamentos": [
    "Raquete 7.5-8.5 oz para começar (leve=controle, pesada=potência)",
    "Tênis de quadra com boa tração lateral",
    "Bolas outdoor são mais pesadas que indoor",
    "Troque grip quando escorregadio, use overgrip",
    "Considere óculos de sol para jogos ao ar livre",
    "Leve toalha, água e bolas extras",
    "Raquete backup para treinos e torneios"
  ],
  "Golpes Fundamentais": [
    "Forehand: movimento de baixo para cima com rotação do corpo",
    "Backhand: use duas mãos para mais controle e potência",
    "Voleio: movimento curto e firme, raquete na frente",
    "Overhead: posicione-se embaixo da bola, use pernas",
    "Dink: movimento suave, raquete aberta, joelhos flexionados",
    "Lob: movimento ascendente, mire alto e profundo",
    "Drop: movimento suave, abra face da raquete",
    "Drive: movimento linear, use corpo para potência",
    "Block: movimento defensivo, absorva velocidade",
    "Reset: movimento ascendente, mire meio da cozinha",
    "Smash: movimento de cima para baixo, use rotação",
    "Erne: salte fora da quadra, timing é crucial",
    "ATP: use ângulo extremo, passe ao lado da rede",
    "Pratique cada golpe isoladamente antes de combinar",
    "Desenvolva consistência antes de potência",
    "Cada golpe tem momento certo para ser usado",
    "Varie golpes para manter adversário adivinhando"
  ],
  "Técnica de Base": [
    "Postura: joelhos flexionados, peso na frente dos pés",
    "Base: pés na largura dos ombros para estabilidade",
    "Equilíbrio: mantenha centro de gravidade baixo",
    "Preparação: raquete sempre na frente do corpo",
    "Seguimento: complete o movimento após contato",
    "Relaxamento: mantenha músculos soltos até o contato",
    "Respiração: expire no momento do contato",
    "Olhos: foque na bola durante todo o movimento",
    "Timing: contato na frente do corpo, não atrás",
    "Ritmo: movimento fluido e coordenado",
    "Consistência: repita mesmo movimento sempre",
    "Ajustes: faça pequenos ajustes, não mudanças grandes",
    "Paciência: desenvolva técnica antes de velocidade",
    "Fundamentos: domine básico antes de avançado",
    "Pratique: repita movimentos até automatizar",
    "Correção: identifique e corrija erros rapidamente",
    "Progressão: aumente dificuldade gradualmente"
  ],
  "Concentração": [
    "Foque apenas no ponto atual, não no placar",
    "Visualize o golpe antes de executar",
    "Mantenha rotina consistente entre pontos",
    "Respire profundamente para se acalmar",
    "Ignore distrações externas (barulho, movimento)",
    "Concentre-se na técnica, não no resultado",
    "Use palavras-chave para manter foco",
    "Mantenha olhos na bola durante todo o movimento",
    "Antecipe onde a bola vai chegar",
    "Prepare-se mentalmente para cada golpe",
    "Mantenha postura confiante e relaxada",
    "Foque no processo, não no resultado",
    "Use timeouts quando perder concentração",
    "Mantenha rotina de preparação consistente",
    "Visualize sucesso antes de cada ponto",
    "Mantenha mente no presente, não no passado",
    "Use respiração para controlar nervos"
  ],
  "Respiração": [
    "Expire no momento do contato com a bola",
    "Inspire durante preparação do golpe",
    "Use respiração para controlar ritmo",
    "Respire profundamente entre pontos",
    "Mantenha respiração regular durante rally",
    "Use respiração para relaxar músculos",
    "Expire com força em golpes de potência",
    "Inspire suavemente em golpes de controle",
    "Respire pelo nariz, expire pela boca",
    "Use respiração para manter foco",
    "Respire de forma rítmica e consistente",
    "Expire completamente antes de novo golpe",
    "Use respiração para controlar nervos",
    "Respire fundo antes de pontos importantes",
    "Mantenha respiração controlada sob pressão",
    "Use respiração para recuperar energia",
    "Respire de forma natural, não forçada"
  ],
  "Drop Shot": [
    "Objetivo: fazer a bola cair na cozinha",
    "Movimento ascendente suave, abra face da raquete",
    "Mire 2-3 pés acima da rede para margem de erro",
    "Use pernas para gerar movimento, não só braços",
    "É melhor errar longo do que curto",
    "Pratique de diferentes distâncias",
    "Varie ocasionalmente para manter adversários honestos",
    "Drop cruzado é mais seguro - mais distância",
    "Use topspin para fazer bola cair mais rápido",
    "Mire para os pés do adversário na cozinha",
    "Drop com underspin é mais difícil de atacar",
    "Varie altura: drop baixo vs alto",
    "Drop para o meio em duplas cria confusão",
    "Pratique drop de diferentes posições na quadra",
    "Drop defensivo: mais alto e profundo",
    "Drop ofensivo: mais baixo e próximo da rede",
    "Observe posição dos adversários antes de dropar",
    "Drop é fundamental para avançar à rede"
  ],
  "Terceira bola": [
    "Crucial para avançar à rede - drop é mais seguro que drive",
    "Permite avançar enquanto bola está no ar",
    "Observe posição dos oponentes antes de escolher",
    "Mire meio da quadra para segurança",
    "Não precisa ser perfeito - só bom o suficiente",
    "Use drive apenas se bola alta e fácil",
    "Pratique transição imediatamente após",
    "Terceira bola cruzada é mais segura",
    "Use topspin para fazer bola cair mais rápido",
    "Mire para os pés do adversário na cozinha",
    "Terceira bola com underspin é mais difícil de atacar",
    "Varie altura: baixa vs alta",
    "Terceira bola para o meio em duplas cria confusão",
    "Pratique terceira bola de diferentes posições",
    "Terceira bola defensiva: mais alta e profunda",
    "Terceira bola ofensiva: mais baixa e próxima da rede",
    "Observe posição dos adversários antes de escolher",
    "Terceira bola é fundamental para controlar o ponto"
  ],
  "Lob": [
    "Use quando oponentes muito próximos da rede",
    "Mire alto e profundo, perto da linha de fundo",
    "Lob com topspin cai mais rápido e é controlável",
    "Disfarce movimento para não telegrafar",
    "Lob defensivo muito alto para ganhar tempo",
    "Use ocasionalmente para manter adversários recuados",
    "Lob para backhand geralmente mais efetivo"
  ],
  "Transição": [
    "Avance em linha reta em etapas: 2-3 passos, split step, repita",
    "Pare e faça split step quando oponente bater",
    "Mantenha raquete baixa para bolas aos pés",
    "Use bloqueios suaves - não tente atacar",
    "Não corra até a cozinha de uma vez",
    "Comunique com parceiro durante transição",
    "Pratique drill repetidamente para automatizar"
  ],
  "Jogo de Duplas": [
    "Movam-se como unidade, não independentemente",
    "Comuniquem constantemente ('minha', 'sua', 'troca')",
    "Jogador à direita geralmente pega bolas no meio",
    "Cubram o meio juntos - não deixem espaços",
    "Mantenham 10-12 pés entre parceiros",
    "Discutam estratégia entre pontos, não durante",
    "Encorajem um ao outro, positividade sempre"
  ],
  "Defesa": [
    "Raquete alta e pronta, joelhos flexionados",
    "Use bloqueios, não swings completos",
    "Absorva velocidade com raquete relaxada",
    "Posicione-se levemente atrás da linha da cozinha",
    "Use resets para neutralizar bolas agressivas",
    "Não recue - mantenha posição na rede",
    "Antecipe ataques observando preparação do oponente"
  ],
  "Bloqueio": [
    "Raquete firme mas não rígida, ângulo para baixo",
    "Bloqueio é posicionamento, não força",
    "Raquete na frente do corpo, movimento mínimo",
    "Use momentum da bola a seu favor",
    "Mire para pés ou espaços abertos",
    "Absorva energia com leve recuo da raquete",
    "Pratique bloqueios de diferentes alturas"
  ],
  "Spin": [
    "Topspin: escove baixo→cima (mergulha, útil em drives)",
    "Backspin: corte por baixo (flutua, útil em dinks/drops)",
    "Sidespin: escove lateralmente para ângulos",
    "Leia spin observando raquete do oponente",
    "Ajuste sua raquete para compensar spin adversário",
    "Use spin para controle, não só para efeito",
    "Spin mais efetivo com raquetes texturizadas"
  ],
  "Contra-ataque": [
    "Identifique bolas altas como oportunidades",
    "Mude defesa→ataque rapidamente",
    "Contra-ataque quando adversário desequilibrado",
    "Acelere bolas que quicam acima da rede",
    "Mantenha bola baixa mesmo ao acelerar",
    "Surpreenda após sequência de dinks",
    "Mantenha controle - não force demais"
  ],
  "Comunicação": [
    "Chame 'minha' alto e claro",
    "Avise 'fora' se bola vai sair",
    "Chame 'troca' ao trocar de lado",
    "Elogie bons golpes do parceiro",
    "Nunca critique durante o jogo",
    "Discuta estratégia entre pontos",
    "Use linguagem corporal positiva"
  ],
  "Drills e Treinos": [
    "Dinking cross-court por 10 minutos",
    "Drill de transição repetidamente",
    "Voleio rápido na rede (hands battle)",
    "Terceira bola drop de diferentes posições",
    "Footwork sem bola para automatizar",
    "Simule situações de pressão (match point)",
    "Trabalhe pontos fracos, não só fortes"
  ],
  "Preparação Física": [
    "Fortaleça core e pernas para estabilidade",
    "Agilidade com escadas e cones",
    "Exercícios de explosão (pliométricos)",
    "Equilíbrio (prancha, single-leg)",
    "Fortaleça rotadores do ombro (previne lesões)",
    "Treino intervalado simula ritmo do jogo",
    "Cardio essencial + dieta balanceada"
  ],
  "Estratégia de Jogo": [
    "Identifique jogador mais fraco e explore",
    "Varie ritmo e colocação para confundir",
    "Jogue percentual em pontos importantes",
    "Analise adversários nos primeiros pontos",
    "Use timeouts para quebrar momentum",
    "Adapte estratégia se não funcionar",
    "Mantenha bola em jogo - force erros"
  ],
  "Tempo de Reação": [
    "Mantenha raquete na posição de preparação",
    "Faça split step quando adversário bate",
    "Antecipe direção observando preparação",
    "Mantenha pés ativos e prontos para mover",
    "Reaja com movimento, não apenas raquete",
    "Pratique drills de reação sem bola",
    "Mantenha olhos na bola constantemente",
    "Use periferia para ver movimento do adversário",
    "Reaja ao som da raquete batendo na bola",
    "Mantenha posição central para reagir a qualquer lado",
    "Pratique com bolas lançadas de diferentes ângulos",
    "Desenvolva reflexos com exercícios específicos",
    "Mantenha mente alerta e concentrada",
    "Reaja instintivamente, não pense demais",
    "Pratique com adversários de diferentes estilos",
    "Mantenha corpo relaxado para reação rápida",
    "Use respiração para manter alerta"
  ],
  "Antecipação": [
    "Observe posição da raquete do adversário",
    "Note padrões de movimento do oponente",
    "Antecipe baseado na posição na quadra",
    "Observe linguagem corporal do adversário",
    "Note direção do olhar do oponente",
    "Antecipe baseado no tipo de golpe",
    "Observe posição dos pés do adversário",
    "Note preparação antes do golpe",
    "Antecipe baseado na altura da bola",
    "Observe padrões de jogo do adversário",
    "Note mudanças no ritmo do oponente",
    "Antecipe baseado no placar",
    "Observe sinais de nervosismo",
    "Note mudanças na postura do adversário",
    "Antecipe baseado no contexto do ponto",
    "Observe reações a diferentes situações",
    "Desenvolva intuição através da prática"
  ],
  "Leitura de Jogo": [
    "Analise estilo de jogo do adversário",
    "Identifique pontos fortes e fracos",
    "Note padrões de colocação de bola",
    "Observe preferências de golpe",
    "Analise posicionamento na quadra",
    "Note reação a diferentes situações",
    "Identifique momento de pressão",
    "Observe comunicação em duplas",
    "Note mudanças de estratégia",
    "Analise consistência do adversário",
    "Observe reação a erros próprios",
    "Note mudanças de ritmo",
    "Analise momento de confiança",
    "Observe sinais de cansaço",
    "Note mudanças de tática",
    "Analise momento de desespero",
    "Desenvolva capacidade de leitura"
  ],
  "Adaptação": [
    "Mude estratégia se não funcionar",
    "Adapte-se ao estilo do adversário",
    "Ajuste posicionamento conforme necessário",
    "Mude ritmo se adversário se adaptar",
    "Ajuste colocação de bola",
    "Mude tipo de golpe se necessário",
    "Adapte-se às condições da quadra",
    "Ajuste tática baseado no placar",
    "Mude abordagem se adversário cansa",
    "Adapte-se ao nível do oponente",
    "Ajuste comunicação em duplas",
    "Mude foco se adversário muda",
    "Adapte-se a diferentes estilos",
    "Ajuste mentalidade conforme necessário",
    "Mude preparação entre pontos",
    "Adapte-se a mudanças de clima",
    "Seja flexível e versátil"
  ],
  "Consistência": [
    "Mantenha mesmo ritmo sempre",
    "Repita movimentos consistentemente",
    "Mantenha foco durante todo o jogo",
    "Não mude técnica durante o jogo",
    "Mantenha posicionamento consistente",
    "Repita rotina entre pontos",
    "Mantenha comunicação em duplas",
    "Não mude estratégia drasticamente",
    "Mantenha nível de energia constante",
    "Repita preparação mental",
    "Mantenha técnica sob pressão",
    "Não mude empunhadura constantemente",
    "Mantenha foco no processo",
    "Repita drills de aquecimento",
    "Mantenha postura confiante",
    "Não mude rotina de jogo",
    "Seja previsível em técnica, imprevisível em tática"
  ],
  "Smash": [
    "Posicione-se embaixo, deixe bola cair até altura ideal",
    "Use rotação completa do corpo + pernas",
    "Contato no ponto mais alto, siga o movimento",
    "Mire para baixo, pés ou espaços abertos",
    "Smash para pés é mais seguro que para fora",
    "Não force se bola não estiver ideal",
    "Pratique timing com bolas lançadas altas",
    "Smash cruzado é mais seguro - mais distância",
    "Use topspin para fazer bola cair mais rápido",
    "Mire para os pés do adversário",
    "Smash com underspin é mais difícil de devolver",
    "Varie altura: smash baixo vs alto",
    "Smash para o meio em duplas cria confusão",
    "Pratique smash de diferentes posições",
    "Smash defensivo: mais alto e profundo",
    "Smash ofensivo: mais baixo e próximo da rede",
    "Observe posição dos adversários antes de smashar",
    "Smash é fundamental para finalizar pontos"
  ],
  "Acelerar as bolas": [
    "Escolha momento certo - não apresse",
    "Acelere bolas acima da altura da rede",
    "Use 70-80% potência para manter controle",
    "Acelere quando adversário desequilibrado",
    "Mire para pés ou ombros, não para fora",
    "Varie entre acelerar e fazer drop",
    "Esteja preparado - bola pode voltar"
  ],
  "Reset": [
    "Absorva velocidade com raquete relaxada",
    "Abra face da raquete, movimento ascendente suave",
    "Mire meio da cozinha para segurança",
    "Use pernas para amortecer impacto",
    "Reset é defesa, não ataque - seja paciente",
    "Mantenha-se baixo e equilibrado",
    "Pratique com parceiro batendo forte"
  ],
  "Ataque": [
    "Ataque apenas bolas altas e favoráveis",
    "Mire para pés ou corpo dos oponentes",
    "Ataque quando tem tempo e posição ideal",
    "Use ângulos para criar espaços vulneráveis",
    "Varie entre potência e colocação",
    "Ataque ao meio em duplas cria confusão",
    "Não ataque se desequilibrado"
  ],
  "Mental Game": [
    "Foque no processo, não no resultado",
    "Respire profundamente entre pontos",
    "Desenvolva rotina entre pontos",
    "Não deixe erros afetarem próximos pontos",
    "Auto-conversa positiva ('vamos lá', 'próximo ponto')",
    "Mantenha-se no presente",
    "Controle o que pode, ignore o resto"
  ],
  "Erne": [
    "Legal apenas se pular fora da quadra",
    "Timing é tudo - antecipe dink cross-court",
    "Salte antes da bola cruzar a rede",
    "Aterrisse fora, não na cozinha",
    "Observe padrão de dinks cruzados do adversário",
    "Comunique com parceiro antes",
    "Use com moderação para manter surpresa"
  ],
  "ATP (Around The Post)": [
    "Apenas possível com ângulo extremo",
    "Bola não precisa passar sobre a rede",
    "Deve passar abaixo da altura da rede",
    "Corra para fora da quadra para melhor ângulo",
    "Oportunidade quando bola muito lateral",
    "Pratique com parceiro criando ângulos extremos",
    "Um dos golpes mais espetaculares!"
  ],
  "Stacking": [
    "Coloca cada jogador em seu lado preferido",
    "Útil quando um tem forehand dominante/backhand fraco",
    "Jogador que não saca fica no lado preferido",
    "Troquem posição após saque/devolução",
    "Requer comunicação clara e prática",
    "Planeje rotação antes do ponto",
    "Comunique quem vai onde antes de cada ponto"
  ],
  "Switching": [
    "Troque quando fizer sentido taticamente",
    "Comunique claramente 'troca' ou 'switch'",
    "Troque quando bola cruza muito para um lado",
    "Jogador com melhor ângulo pega a bola",
    "Use para cobrir lobs ou bolas profundas",
    "Evite trocar em meio a rally rápido",
    "Pratique em treinos antes de usar em jogos"
  ],
  "Poaching": [
    "Intercepte apenas se tiver certeza",
    "Poach em bolas no meio da quadra",
    "Jogador com forehand geralmente poach mais",
    "Observe padrões de devolução dos oponentes",
    "Use elemento surpresa - não seja previsível",
    "Comunique intenção com parceiro",
    "Não exagere - pode expor parceiro"
  ],
  "Finalizações": [
    "Identifique bolas altas como oportunidades",
    "Não apresse - espere a bola certa",
    "Finalize quando bola acima da rede",
    "Use ângulos para dificultar defesa",
    "Varie entre potência e colocação",
    "Finalize para pés em bolas médias",
    "Mire espaços abertos, mantenha controle"
  ],
  "Jogo Singles": [
    "Condicionamento é crucial - cubra mais quadra",
    "Use lobs e drives profundos",
    "Explore cantos, movimente oponente",
    "Recupere sempre para o centro",
    "Use drop shots para trazer adversário à frente",
    "Varie entre cruzado e paralelo",
    "Seja paciente - pontos são mais longos"
  ],
  "Torneios": [
    "Chegue cedo para aquecer adequadamente",
    "Traga água, snacks, equipamento extra + backup",
    "Mantenha rotina pré-jogo consistente",
    "Hidrate-se e coma leve entre jogos",
    "Descanse entre partidas",
    "Estude adversários e chaveamento",
    "Mentalidade positiva independente de resultados"
  ],
  "Golpes Especiais": [
    "Erne: salte fora da quadra, timing perfeito",
    "ATP: use ângulo extremo, passe ao lado da rede",
    "Around the post: bola deve passar abaixo da rede",
    "Behind the back: use quando bola passa por trás",
    "Between the legs: use quando bola está muito baixa",
    "No-look shot: use quando adversário não espera",
    "Fake shot: disfarce direção até último momento",
    "Drop volley: voleio que cai na cozinha",
    "Lob volley: voleio alto e profundo",
    "Cross-court angle: use ângulos extremos",
    "Down the line: use quando adversário espera cruzado",
    "Body shot: mire no corpo do adversário",
    "Chip shot: use underspin para confundir",
    "Slice shot: use para mudar ritmo",
    "Topspin lob: use para passar por cima",
    "Backhand smash: use quando bola está no backhand",
    "Pratique golpes especiais em treinos"
  ],
  "Técnicas Avançadas": [
    "Spin reverso: use para confundir adversário",
    "Mudança de direção: mude no último momento",
    "Fake: disfarce intenção até o contato",
    "Timing perfeito: contato no momento ideal",
    "Placement preciso: mire em pontos específicos",
    "Power control: controle potência com precisão",
    "Angle creation: crie ângulos impossíveis",
    "Depth variation: varie profundidade constantemente",
    "Height variation: varie altura das bolas",
    "Speed variation: varie velocidade constantemente",
    "Spin variation: varie tipos de spin",
    "Direction change: mude direção rapidamente",
    "Pace control: controle ritmo do jogo",
    "Pressure building: construa pressão gradualmente",
    "Momentum shifting: mude momentum do jogo",
    "Clutch performance: execute sob pressão",
    "Master the basics before advanced techniques"
  ],
  "Pressão Mental": [
    "Mantenha calma sob pressão",
    "Respire profundamente em momentos tensos",
    "Foque no processo, não no resultado",
    "Use rotina consistente para relaxar",
    "Visualize sucesso antes de executar",
    "Mantenha postura confiante",
    "Não mostre nervosismo para adversário",
    "Use timeouts quando necessário",
    "Mantenha foco no presente",
    "Não pense em erros passados",
    "Mantenha energia positiva",
    "Use auto-conversa positiva",
    "Mantenha ritmo consistente",
    "Não mude técnica sob pressão",
    "Mantenha comunicação em duplas",
    "Use respiração para controlar nervos",
    "Confie no seu treinamento"
  ],
  "Execução Sob Pressão": [
    "Mantenha técnica consistente",
    "Não mude estratégia drasticamente",
    "Foque na execução, não no resultado",
    "Mantenha rotina entre pontos",
    "Respire profundamente antes de executar",
    "Visualize o golpe antes de fazer",
    "Mantenha postura confiante",
    "Não pense em consequências",
    "Mantenha foco no presente",
    "Execute com confiança",
    "Mantenha ritmo normal",
    "Não se apresse",
    "Mantenha comunicação clara",
    "Use experiência de treinos",
    "Mantenha energia positiva",
    "Confie no seu jogo",
    "Execute como se fosse treino"
  ],
  "Liderança em Quadra": [
    "Seja exemplo positivo para parceiro",
    "Mantenha comunicação constante",
    "Motive parceiro em momentos difíceis",
    "Tome decisões rápidas e claras",
    "Mantenha energia positiva sempre",
    "Seja responsável por erros próprios",
    "Ajude parceiro a melhorar",
    "Mantenha foco no objetivo comum",
    "Seja paciente com parceiro",
    "Mantenha calma em situações tensas",
    "Seja líder pelo exemplo",
    "Mantenha comunicação construtiva",
    "Seja apoio para parceiro",
    "Mantenha espírito de equipe",
    "Seja humilde em vitórias",
    "Mantenha determinação em derrotas",
    "Seja inspiração para outros"
  ],

  // Táticas
  "Controle de Ritmo": [
    "Use dinks para desacelerar, acelere quando oponentes confortáveis",
    "Controle tempo entre pontos - respire e planeje",
    "Use timeouts para quebrar momentum adversário",
    "Ritmo lento favorece pacientes, rápido favorece agressivos",
    "Mude ritmo após perder 2-3 pontos seguidos",
    "Observe quando adversários ficam impacientes",
    "Controle ritmo com profundidade e colocação",
    "Ritmo lento: dinks longos e profundos",
    "Ritmo rápido: drives e voleios agressivos",
    "Varie ritmo dentro do mesmo rally",
    "Use ritmo para tirar adversário da zona de conforto",
    "Ritmo defensivo: mantenha bola em jogo",
    "Ritmo ofensivo: force decisões rápidas",
    "Observe como adversário reage a diferentes ritmos",
    "Controle ritmo com altura e spin das bolas",
    "Use pausas estratégicas para quebrar concentração",
    "Ritmo consistente cansa adversários inconsistentes"
  ],
  "Jogo no Meio": [
    "Mire na linha divisória entre os jogadores",
    "Meio cria confusão sobre quem pega a bola",
    "Bolas no meio = devoluções mais fracas",
    "Use meio em terceira bola para neutralizar",
    "Funciona melhor quando oponentes estão largos",
    "Ataque meio quando adversários não se comunicam",
    "Varie entre meio e laterais",
    "Meio em dinks é mais seguro",
    "Meio em voleios cria confusão máxima",
    "Use meio para forçar comunicação entre adversários",
    "Meio funciona melhor contra duplas que não se comunicam",
    "Varie altura: meio baixo vs alto",
    "Meio defensivo: mais alto e profundo",
    "Meio ofensivo: mais baixo e próximo da rede",
    "Observe posição dos adversários antes de jogar no meio",
    "Meio é fundamental para quebrar ritmo do adversário",
    "Pratique precisão para acertar a linha divisória"
  ],
  "Explorar Fraquezas": [
    "Observe primeiros pontos para identificar fraquezas",
    "Teste backhand de ambos cedo",
    "Note dificuldade com bolas altas/baixas, rápidas/lentas",
    "Identifique jogador menos móvel e footwork fraco",
    "Explore fraqueza mental (nervosismo, impaciência)",
    "Mantenha pressão constante na fraqueza",
    "Adapte se adversários corrigirem"
  ],
  "Variação de Altura": [
    "Alterne dinks baixos, drives médios, lobs ocasionais",
    "Bolas na altura dos ombros são difíceis de controlar",
    "Bolas baixas forçam adversário a bater de baixo→cima",
    "Bolas altas testam overhead e paciência",
    "Varie altura dentro do mesmo rally",
    "Use para tirar adversário da zona de conforto",
    "Combine variação de altura + velocidade"
  ],
  "Pressão Constante": [
    "Mantenha profundidade, não dê bolas fáceis",
    "Coloque cada bola com propósito",
    "Seja consistente - force adversário a fazer algo especial",
    "Pressão cansa física e mentalmente",
    "Não dê tempo para respirar ou pensar",
    "Mantenha bola em jogo - force adversário a ganhar",
    "Pressão quebra jogadores inconsistentes"
  ],
  "Jogo Cruzado": [
    "Dinks cruzados têm mais margem de erro",
    "Cruzado tem mais distância - mais tempo para reagir",
    "Use para abrir ângulos e construir ponto",
    "Cruzado é mais seguro sob pressão",
    "Permite melhor recuperação de posição",
    "Combine cruzado com paralelo ocasional",
    "Fundamental em jogo de duplas"
  ],
  "Isolamento de Jogador": [
    "Identifique jogador mais fraco nos primeiros pontos",
    "Direcione 70-80% das bolas para o alvo",
    "Isole também jogador cansado em jogos longos",
    "Isolamento cria frustração e tensão na dupla",
    "Jogador isolado tende a cometer mais erros",
    "Use especialmente em pontos importantes",
    "Varie ocasionalmente para manter surpresa"
  ],
  "Mudança de Direção": [
    "Não seja previsível - varie constantemente",
    "Mudanças bruscas são mais efetivas",
    "Use após sequência no mesmo lado",
    "Força adversário a ajustar footwork",
    "Use quando adversário se movendo em uma direção",
    "Combine com variação de velocidade",
    "Mudanças frequentes cansam adversário"
  ],
  "Jogo de Paciência": [
    "Nem todo ponto precisa ser rápido",
    "Espere a bola certa para atacar",
    "Paciência frustra jogadores agressivos",
    "Construa ponto até criar oportunidade",
    "Não force ataques - deixe adversário errar",
    "Especialmente importante em dinking",
    "Pratique pontos longos em treinos"
  ],
  "Ataque ao Corpo": [
    "Mire entre ombros e quadris",
    "Limita opções de resposta do adversário",
    "Especialmente efetivo em voleios rápidos",
    "Use quando adversário muito perto da rede",
    "Jogador não pode usar forehand/backhand completo",
    "Efetivo contra jogadores com boa cobertura lateral",
    "Combine com ataques aos pés"
  ],
  "Uso do Lob Tático": [
    "Lob não é só defesa - use ofensivamente",
    "Força adversários a recuar da rede",
    "Use para quebrar ritmo de dinking",
    "Lob após sequência de bolas baixas surpreende",
    "Cria oportunidade de avançar para rede",
    "Lob ocasional mantém adversários recuados",
    "Pratique lobs com topspin para controle"
  ],
  "Forçar Erros": [
    "Coloque bolas em posições desconfortáveis",
    "Mantenha profundidade para limitar opções",
    "Varie colocação para criar incerteza",
    "Jogue para fraquezas",
    "Mantenha consistência - adversário eventualmente erra",
    "Pressão mental força mais erros que física",
    "Seja paciente - deixe adversário se auto-destruir"
  ],
  "Estratégias de Abertura": [
    "Comece com saque profundo e bem colocado",
    "Use devolução cruzada para abrir ângulos",
    "Avance à rede após terceira bola",
    "Estabeleça controle do ponto desde o início",
    "Varie abertura para não ser previsível",
    "Use abertura para testar fraquezas do adversário",
    "Mantenha pressão desde o primeiro golpe",
    "Abertura deve colocar adversário em desvantagem",
    "Use abertura para controlar ritmo do jogo",
    "Abertura deve criar oportunidades de ataque",
    "Varie entre abertura agressiva e conservadora",
    "Use abertura para forçar erros do adversário",
    "Abertura deve colocar adversário em posição defensiva",
    "Use abertura para controlar centro da quadra",
    "Abertura deve criar confusão na dupla adversária",
    "Varie altura e velocidade na abertura",
    "Abertura deve estabelecer domínio do ponto"
  ],
  "Controle de Ponto": [
    "Mantenha iniciativa durante todo o ponto",
    "Force adversário a reagir às suas jogadas",
    "Controle ritmo e direção do rally",
    "Mantenha adversário em posição defensiva",
    "Use variação para quebrar ritmo do adversário",
    "Controle centro da quadra sempre que possível",
    "Force adversário a fazer jogadas difíceis",
    "Mantenha pressão constante sem forçar",
    "Controle altura e profundidade das bolas",
    "Force adversário a se mover constantemente",
    "Mantenha adversário longe da zona de conforto",
    "Controle tempo entre golpes",
    "Force adversário a tomar decisões rápidas",
    "Mantenha adversário em posição desconfortável",
    "Controle direção e ângulo das bolas",
    "Force adversário a cometer erros",
    "Mantenha domínio tático do ponto"
  ],
  "Quebra de Ritmo": [
    "Varie velocidade das bolas constantemente",
    "Use pausas estratégicas entre pontos",
    "Alterne entre golpes altos e baixos",
    "Varie direção das bolas frequentemente",
    "Use mudanças bruscas de ritmo",
    "Alterne entre agressivo e defensivo",
    "Varie tempo de preparação entre golpes",
    "Use fakes para confundir adversário",
    "Alterne entre potência e controle",
    "Varie altura das bolas constantemente",
    "Use mudanças de direção inesperadas",
    "Alterne entre cruzado e paralelo",
    "Varie profundidade das bolas",
    "Use mudanças de spin constantemente",
    "Alterne entre ataque e construção",
    "Varie ângulo das bolas",
    "Mantenha adversário sempre adivinhando"
  ],
  "Exploração de Ângulos": [
    "Use ângulos extremos para criar espaços",
    "Mire nas linhas laterais e de fundo",
    "Crie ângulos impossíveis de defender",
    "Use ângulos para forçar movimento do adversário",
    "Varie ângulos constantemente",
    "Use ângulos para abrir quadra",
    "Crie ângulos que forçam devoluções fracas",
    "Use ângulos para controlar centro da quadra",
    "Varie entre ângulos agudos e obtusos",
    "Use ângulos para quebrar defesa",
    "Crie ângulos que confundem dupla adversária",
    "Use ângulos para forçar erros",
    "Varie ângulos de ataque e defesa",
    "Use ângulos para controlar ritmo",
    "Crie ângulos que forçam decisões rápidas",
    "Use ângulos para dominar o ponto",
    "Varie ângulos para manter surpresa"
  ],
  "Jogos Mentais": [
    "Use linguagem corporal para confundir",
    "Mantenha expressão neutra sempre",
    "Use pausas para quebrar concentração",
    "Varie tempo de preparação entre golpes",
    "Use fakes para enganar adversário",
    "Mantenha adversário sempre adivinhando",
    "Use mudanças bruscas de estratégia",
    "Mantenha adversário em estado de incerteza",
    "Use pressão mental constante",
    "Mantenha adversário fora da zona de conforto",
    "Use variação para confundir padrões",
    "Mantenha adversário reagindo às suas jogadas",
    "Use tempo para controlar ritmo",
    "Mantenha adversário em posição defensiva",
    "Use mudanças para quebrar momentum",
    "Mantenha adversário sempre pensando",
    "Use estratégia para dominar mentalmente"
  ],
  "Adaptação Tática": [
    "Mude estratégia se não funcionar",
    "Adapte-se ao estilo do adversário",
    "Ajuste tática baseado no placar",
    "Mude abordagem se adversário se adapta",
    "Adapte-se às condições da quadra",
    "Ajuste tática baseado no cansaço",
    "Mude estratégia se adversário muda",
    "Adapte-se ao nível do oponente",
    "Ajuste tática baseado no contexto",
    "Mude abordagem se não funcionar",
    "Adapte-se a diferentes situações",
    "Ajuste tática baseado no momento",
    "Mude estratégia se adversário cansa",
    "Adapte-se a mudanças de clima",
    "Ajuste tática baseado na pressão",
    "Mude abordagem se adversário muda",
    "Seja flexível e versátil sempre"
  ]
};

